### ISSUE TITLE
Styling markers

### ISSUE THREAD

**Issue by mattmcnabb** [tyleruebele/details-shim#6]
In Chrome I can hide the detail markers using:

```css
details::-webkit-details-marker {
    display: none;
}
```

Will this script handle a scenario like that?
